import { Sparkles, Info } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";

interface Props {
  systemName?: string;
  variant?: "chat" | "graded" | "content" | "synthetic";
  className?: string;
}

const COPY: Record<NonNullable<Props["variant"]>, string> = {
  chat: "You are interacting with an AI tutor. Responses are generated by a language model and may be inaccurate. AI tutors do not replace human faculty guidance.",
  graded: "This assessment was scored with AI assistance. Under the EU AI Act (Art. 86), you have the right to a meaningful explanation and to request human review of any AI-influenced decision.",
  content: "Portions of this content were generated with AI assistance and reviewed against ScrollUniversity's editorial standards.",
  synthetic: "This lecture uses a synthetic AI-generated voice and/or avatar. The underlying instruction was authored or approved by faculty.",
};

export const AIDisclosureBanner = ({ systemName, variant = "chat", className = "" }: Props) => (
  <Alert className={`border-accent/30 bg-accent/5 ${className}`}>
    <Sparkles className="h-4 w-4 text-accent" />
    <AlertDescription className="text-xs font-sans text-foreground/80 leading-relaxed">
      <span className="font-semibold">AI Disclosure{systemName ? ` — ${systemName}` : ""}:</span>{" "}
      {COPY[variant]}{" "}
      <a href="/ai-transparency" className="underline underline-offset-2 hover:text-primary inline-flex items-center gap-1">
        <Info className="h-3 w-3" /> Learn more
      </a>
    </AlertDescription>
  </Alert>
);
