import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { toast } from "sonner";

const KINDS = ["certificate","diploma","associate","bachelor","master","doctorate","supreme","honor"] as const;
type Kind = typeof KINDS[number];

interface Cred {
  id: string;
  student_id: string;
  kind: string;
  title: string;
  program_ref: string | null;
  issued_at: string;
  status: string;
  verification_token: string;
}

export default function CredentialIssuanceAdmin() {
  const [form, setForm] = useState({
    student_id: "", kind: "certificate" as Kind, title: "", program_ref: "",
    expires_on: "",
  });
  const [eligibility, setEligibility] = useState<{ eligible: boolean; reason: string } | null>(null);
  const [creds, setCreds] = useState<Cred[]>([]);
  const [revokeId, setRevokeId] = useState<string | null>(null);
  const [revokeReason, setRevokeReason] = useState("");

  const refresh = async () => {
    const { data } = await supabase.from("issued_credentials").select("*")
      .order("issued_at", { ascending: false }).limit(50);
    setCreds((data as Cred[]) || []);
  };
  useEffect(() => { refresh(); }, []);

  const checkEligibility = async () => {
    if (!form.student_id) return;
    const { data, error } = await supabase.rpc("check_credential_eligibility", {
      p_student_id: form.student_id, p_kind: form.kind,
    });
    if (error) { toast.error(error.message); return; }
    const row = Array.isArray(data) ? data[0] : null;
    if (row) setEligibility({ eligible: row.eligible, reason: row.reason });
  };

  const issue = async () => {
    if (!form.student_id || !form.title) { toast.error("Student ID and title required"); return; }
    const { data: gpaRow } = await supabase.rpc("compute_student_gpa", { p_student_id: form.student_id });
    const stats: any = Array.isArray(gpaRow) ? gpaRow[0] : gpaRow;
    const { error } = await supabase.from("issued_credentials").insert({
      student_id: form.student_id,
      kind: form.kind,
      title: form.title,
      program_ref: form.program_ref || null,
      expires_on: form.expires_on || null,
      seal_hash: "", // Auto-generated by trigger
      snapshot: {
        gpa: stats?.gpa ?? stats?.cumulative_gpa ?? null,
        total_credit_hours: stats?.total_credit_hours ?? stats?.cumulative_credits_earned ?? 0,
        issued_at: new Date().toISOString(),
        kind: form.kind,
        title: form.title,
      },
    });
    if (error) toast.error(error.message);
    else { toast.success("Credential issued"); refresh(); }
  };

  const revoke = async (id: string) => {
    if (!revokeReason.trim()) { toast.error("Reason required"); return; }
    const { error: e1 } = await supabase.from("issued_credentials")
      .update({ status: "revoked", revoke_reason: revokeReason, revoked_at: new Date().toISOString() })
      .eq("id", id);
    if (e1) { toast.error(e1.message); return; }
    await supabase.from("credential_revocations").insert({ credential_id: id, reason: revokeReason });
    toast.success("Credential revoked");
    setRevokeId(null); setRevokeReason("");
    refresh();
  };

  return (
    <div className="container mx-auto py-8 space-y-6">
      <h1 className="font-serif text-4xl">Credential Issuance & Verification</h1>

      <Card>
        <CardHeader><CardTitle>Issue Credential</CardTitle></CardHeader>
        <CardContent className="grid md:grid-cols-2 gap-3">
          <div><Label>Student ID</Label><Input value={form.student_id} onChange={e => setForm({ ...form, student_id: e.target.value })} /></div>
          <div>
            <Label>Kind</Label>
            <select className="w-full border rounded h-10 px-2 bg-background"
              value={form.kind} onChange={e => setForm({ ...form, kind: e.target.value as Kind })}>
              {KINDS.map(k => <option key={k} value={k}>{k}</option>)}
            </select>
          </div>
          <div><Label>Title</Label><Input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="Bachelor of Theology" /></div>
          <div><Label>Program ref</Label><Input value={form.program_ref} onChange={e => setForm({ ...form, program_ref: e.target.value })} /></div>
          <div><Label>Expires on (optional)</Label><Input type="date" value={form.expires_on} onChange={e => setForm({ ...form, expires_on: e.target.value })} /></div>
          <div className="md:col-span-2 flex gap-2 items-center">
            <Button variant="outline" onClick={checkEligibility}>Check eligibility gate</Button>
            <Button onClick={issue} disabled={eligibility?.eligible === false}>Issue credential</Button>
            {eligibility && (
              <Badge variant={eligibility.eligible ? "default" : "destructive"}>
                {eligibility.eligible ? "Eligible" : "Blocked"}: {eligibility.reason}
              </Badge>
            )}
          </div>
          <p className="md:col-span-2 text-xs text-muted-foreground">
            The eligibility gate enforces credit-hour and GPA thresholds for graduate-tier credentials.
            Issuance is permanent; corrections happen only via revocation + re-issuance.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader><CardTitle>Recently Issued</CardTitle></CardHeader>
        <CardContent>
          <Table>
            <TableHeader><TableRow>
              <TableHead>Title</TableHead><TableHead>Kind</TableHead><TableHead>Issued</TableHead>
              <TableHead>Status</TableHead><TableHead>Token</TableHead><TableHead></TableHead>
            </TableRow></TableHeader>
            <TableBody>
              {creds.map(c => (
                <TableRow key={c.id}>
                  <TableCell>{c.title}</TableCell>
                  <TableCell className="capitalize">{c.kind}</TableCell>
                  <TableCell>{new Date(c.issued_at).toLocaleDateString()}</TableCell>
                  <TableCell><Badge variant={c.status === "issued" ? "default" : "destructive"}>{c.status}</Badge></TableCell>
                  <TableCell className="font-mono text-xs">{c.verification_token.slice(0, 12)}…</TableCell>
                  <TableCell>
                    {c.status === "issued" && (
                      revokeId === c.id ? (
                        <div className="flex gap-1">
                          <Input className="h-8 text-xs" placeholder="Reason" value={revokeReason} onChange={e => setRevokeReason(e.target.value)} />
                          <Button size="sm" variant="destructive" onClick={() => revoke(c.id)}>Revoke</Button>
                        </div>
                      ) : (
                        <Button size="sm" variant="outline" onClick={() => setRevokeId(c.id)}>Revoke…</Button>
                      )
                    )}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
